#!/usr/bin/env bash
# Writes a wrapper kustomization that pins images and optionally retargets the
# namespace, without the app repo committing an `images:` block.
#
#   make-wrapper.sh <out_dir> <overlay_ref> [namespace] < pins.tsv
#
# pins.tsv is one line per image: <name>\t<newName>\t<newTag>. An empty
# newName keeps the image name and changes only the tag.
#
# overlay_ref is written verbatim into `resources:`, so it must be relative to
# out_dir (e.g. ../kustomize/overlays/prod).
set -eu

out=${1:-}
overlay=${2:-}
ns=${3:-}

if [ -z "$out" ] || [ -z "$overlay" ]; then
    echo "usage: $0 <out_dir> <overlay_ref> [namespace] < pins.tsv" >&2
    exit 1
fi

pins=$(cat)
if [ -z "$pins" ]; then
    echo "make-wrapper: no image pins on stdin" >&2
    exit 1
fi

mkdir -p "$out"

{
    echo "# Generated by actions-system. Not committed by the app repo."
    echo "resources:"
    echo "  - $overlay"
    if [ -n "$ns" ]; then
        echo "namespace: $ns"
    fi
    echo "images:"
    printf '%s\n' "$pins" | while IFS="$(printf '\t')" read -r name newname newtag; do
        [ -n "$name" ] || continue
        # Tab is IFS whitespace, so `read` collapses consecutive tabs and a
        # line with an empty middle field arrives as two fields, putting the
        # tag in newname and leaving newtag empty. Refuse it: the alternative
        # is a wrapper that renames the image to its own tag and applies
        # cleanly. Callers must always send all three fields.
        if [ -z "$newtag" ]; then
            echo "make-wrapper: malformed pin for '$name' — expected <name><TAB><newName><TAB><newTag>" >&2
            exit 1
        fi
        echo "  - name: $name"
        if [ -n "$newname" ]; then
            echo "    newName: $newname"
        fi
        echo "    newTag: $newtag"
    done
} > "$out/kustomization.yaml"
